# Generated by Django 4.2.9 on 2024-03-10 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "investment_horizon",
                    models.CharField(
                        choices=[
                            ("short_term", "Short Term"),
                            ("medium_term", "Medium Term"),
                            ("long_term", "Long Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "liquidity_needs",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "investment_objective",
                    models.CharField(
                        choices=[
                            ("capital_preservation", "Capital Preservation"),
                            ("income_generation", "Income Generation"),
                            ("wealth_accumulation", "Wealth Accumulation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "knowledge_experience",
                    models.CharField(
                        choices=[
                            ("novice", "Novice"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sectors", models.CharField(max_length=200)),
                (
                    "available_funds",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferences",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.preferences",
            ),
        ),
    ]
