# Generated by Django 4.2.9 on 2024-03-25 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_preferences_customuser_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferences",
            name="sectors",
            field=models.CharField(
                choices=[
                    ("banks", "Banks"),
                    ("leasing", "Leasing"),
                    ("others", "Others"),
                    ("all", "All"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
