# Generated by Django 4.2.9 on 2024-04-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_forumpost_forumcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="face_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
    ]
