# Generated by Django 4.2.9 on 2024-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_customuser_face_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="face_image",
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_photos/"),
        ),
    ]
