# Generated by Django 4.2.9 on 2024-04-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_customuser_face_image_customuser_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="photo",
        ),
    ]
