# Generated by Django 4.2.9 on 2024-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_userimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registered_images",
            field=models.JSONField(default=list),
        ),
    ]
