# Generated by Django 4.2.9 on 2024-04-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_customuser_registered_images"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserImage",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="registered_images",
        ),
    ]
