# Generated by Django 4.2.9 on 2024-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_delete_userimage_remove_customuser_registered_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferences",
            name="liquidity_needs",
        ),
        migrations.AlterField(
            model_name="preferences",
            name="sectors",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("assurance", "Assurance"),
                    ("banks", "Banks"),
                    ("leasing", "Leasing"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
